Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.host_name = "postgresql"
  config.vm.provision :shell, :path => "bootstrap.sh"
  # PostgreSQL Server port forwarding
  config.vm.network "forwarded_port", guest: 5432, host: 15432
end